BMC_01:
  ip_address: 192.2.16.44
  password: superuser
  username: sysadmin
BMC_02:
  ip_address: 192.2.16.151
  password: superuser
  username: sysadmin
BMC_03:
  ip_address: 192.2.16.44
  password: 9ijn0okm
  username: taobao
