# 注意缩进
FW-VERSION:
  # bios fw version
  bios_ver: '3.0.ES.AL.P.066.04'
  bios_ver_for_at: '3.0.ES.AL.P.066.04'
  # 机头bmc fw version
  header_bmc_ver: '7.27'
  header_bmc_ver_for_at: '7.25'
  # 机尾bmc fw version
  tail_bmc_ver: '7.16.13'
  # 机头cpld fw version
  cpuboard_ver: '3.12'
  cmuboard_ver: '3.11'
  # mcx nic fw version
  mcx6_ver: '22.35.1012'
  # oam fw version
  oam_ver: '1.4.44'
  # HIB fw version
  hib_ver: '0x05'
  ubb1: '0x08'
  ubb2: '0x04'
  fanbp80: '0x16'
  fanbp40: '0x03'
  nvmebp1: '0x14'
  nvmebp2: '0x14'
  nvme_ver: 'JCV102S1'
  target_retimer_ver: '123456'
  # pcie switch fw version 4:4上行 8：8上行
  switch_ver:
    4: "04.101.00.001"
    8: "04.101.00.001"
  psu:
    header_psu: "00.10.11"
    tail_psu: "00.05.06"
  
  # retimer
  retimer_ver:
    header_a: "2.2.36"
    header_m: "06_6A_A4_00"
    tail_a: "2.2.1"
    tail_m: "06_6A_A0_01"

DEVICE_COUNT:
  nic_count: '1'