# 命令行参数
UUT: {
    'default': 'UUT_01',
    'type': 'str',
    'help': 'Select UUT for test',
}

CaseCycle: {
    'default': 1,
    'type': 'int',
    'help': 'Test a case Cycle',
}

# 机尾
JBOG_BMC: {
    'default': 'BMC_01',
    'type': 'str',
    'help': 'Select jbog BMC for test',
}

# 机头
SERVER_BMC: {
    'default': 'BMC_02',
    'type': 'str',
    'help': 'Select server BMC for test',
}

SuiteCycle: {
    'default': 1,
    'type': 'int',
    'help': 'Test Batch Case Cycle',
}

SuiteStop: {
    'default': "yes",
    'type': 'str',
    'help': 'Start Suite Test',
}
#
#SuiteConfPath: {
#  'default': "",
#  'type': 'str',
#  'help': 'Start Suite csv file path',
#}
#
#SuiteConf: {
#  'default': "",
#  'type': 'str',
#  'help': 'Start Suite csv file',
#}

FailStop: {
    'default': 'yes',
    'type': 'str',
    'help': 'Test Suite Fail Stop, [yes/no], yes: stop the after case test, no: continue doing case test',
}

LogFlag: {
    'default': 'debug',
    'type': 'str',
    'help': 'set the log level as debug or normal mode',
}

SubLog: {
    'default': '',
    'type': 'str',
    'help': 'batch run sub log file dir',
}

Log_file: {
    'default': '',
    'type': 'str',
    'help': 'log file dir',
}

LogPath: {
    'default': '',
    'type': 'str',
    'help': 'log file save path',
}

PUT: {
    'default': 'PUT1',
    'type': 'str',
    'help': 'batch run select PUT config',
}

CSV: {
    'default': 'PT.csv',
    'type': 'str',
    'help': 'default execute script, Config/PT.csv file ',
}


PDU: {
    'default': 'PDU_01',
    'type': 'str',
    'help': 'Select UUT for test',
}



